apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-cluster-ready
  namespace: openshift-monitoring
rules:
# SRE can get, list, and watch all resources
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
