apiVersion: batch/v1
kind: Job
metadata:
    name: osd-cluster-ready
    namespace: openshift-monitoring
spec:
    template:
        metadata:
            name: osd-cluster-ready
        spec:
            containers:
            # TODO: Remove this override once
            # https://bugzilla.redhat.com/show_bug.cgi?id=1921413
            # is resolved
            - env:
              - name: MAX_CLUSTER_AGE_MINUTES
                value: "240"
              name: osd-cluster-ready
              image: quay.io/openshift-sre/osd-cluster-ready
              imagePullPolicy: Always
              command: ["/root/main"]
            restartPolicy: OnFailure
            serviceAccountName: osd-cluster-ready
